<a href="https://colab.research.google.com/github/FabrizioBettetti/Machine-learning/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

In [2]:
numpy.__version__

'2.0.2'

In [3]:
import numpy as np   #Efficient storage AND operations

In [4]:
np?

In [5]:
import array   #Fixed-type data buffer. Efficient storage

In [6]:
L = list(range(10))
A = array.array('i', L)   #'i': integer
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x = np.array(12)
x

array(12)

In [8]:
x.ndim

0

In [9]:
x = np.array([12, 3, 6, 14, 7])
x

array([12,  3,  6, 14,  7])

In [10]:
x.ndim

1

In [11]:
np.array([3.14, 4, 2, 3])   #Upcasting

array([3.14, 4.  , 2.  , 3.  ])

In [12]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [13]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
x.ndim

2

In [15]:
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
x.ndim

3

In [16]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [19]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
np.random.random((3, 3))   #Uniform distribution in [0, 1)

array([[0.65485772, 0.12293182, 0.86292756],
       [0.67226169, 0.09495698, 0.70982062],
       [0.31535409, 0.75026962, 0.80165024]])

In [22]:
np.random.normal(0, 1, (3, 3))   #Normal distribution with mean = 0 and standard deviation = 1

array([[ 0.5716978 ,  1.31704932, -0.07583928],
       [-1.10749595,  0.86253981, -0.73847401],
       [-0.14497081, -1.06481475,  0.72202134]])

In [23]:
np.random.randint(0, 10, (3, 3))   #Discrete uniform distribution in [0, 10)

array([[1, 1, 4],
       [2, 2, 3],
       [2, 8, 1]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
#Create an uninitialized array of three integers.
#The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [26]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [27]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [28]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))
#Discrete uniform distribution in [0, 10)

In [29]:
print('x3 ndim:', x3.ndim)
print('x3 shape:', x3.shape)
print('x3 size:', x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [30]:
print('dtype:', x3.dtype)

dtype: int64


In [31]:
print('itemsize:', x3.itemsize, 'bytes')
print('nbytes:', x3.nbytes, 'bytes')

itemsize: 8 bytes
nbytes: 480 bytes


In [32]:
x1

array([5, 0, 3, 3, 7, 9])

In [33]:
x1[0]

np.int64(5)

In [34]:
x1[4]

np.int64(7)

In [35]:
x1[-1]

np.int64(9)

In [36]:
x1[-2]

np.int64(7)

In [37]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [38]:
x2[0, 0]

np.int64(3)

In [39]:
x2[2, 0]

np.int64(1)

In [40]:
x2[2, -1]

np.int64(7)

In [41]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [42]:
x1[0] = 3.14159   #Truncated because of integer dtype array
x1

array([3, 0, 3, 3, 7, 9])

In [43]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x[:5]

array([0, 1, 2, 3, 4])

In [45]:
x[5:]

array([5, 6, 7, 8, 9])

In [46]:
x[4:7]

array([4, 5, 6])

In [47]:
x[::2]

array([0, 2, 4, 6, 8])

In [48]:
x[1::2]

array([1, 3, 5, 7, 9])

In [49]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [50]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
x[5::-2]

array([5, 3, 1])

In [52]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [53]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [54]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [55]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [56]:
x2[:, 0]

array([12,  7,  1])

In [57]:
print(x2[:, 0])

[12  7  1]


In [58]:
x2[0, :]

array([12,  5,  2,  4])

In [59]:
print(x2[0, :])

[12  5  2  4]


In [60]:
print(x2[0])   #Equivalent to x2[0, :]. Only in case of row access!

[12  5  2  4]


In [61]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [62]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [63]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [64]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [65]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [66]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [67]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [68]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [70]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [71]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [72]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [73]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [74]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [75]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])   #Concatenate along the first axis

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [76]:
np.concatenate([grid, grid], axis=1)   #Concatenate along the second axis

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [77]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [78]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [79]:
def naive_relu(x):
  assert len(x.shape) == 2
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] = max(x[i, j], 0)
  return x

In [80]:
def naive_add(x, y):
  assert len(x.shape) == 2
  assert x.shape == y.shape
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] += y[i, j]
  return x

In [81]:
import time

x = np.random.random((20, 100))   #Matrix 20 x 100
y = np.random.random((20, 100))

t0 = time.time()
for _ in range(1000):
  z = x + y
  z = np.maximum(z, 0.)
print('Took: {0:.2f} s'.format(time.time() - t0))

Took: 0.02 s


In [82]:
t0 = time.time()
for _ in range(1000):
  z = naive_add(x, y)
  z = naive_relu(z)
print('Took: {0:.2f} s'.format(time.time() - t0))

Took: 6.49 s


In [83]:
import numpy as np

#Broadcast
x = np.random.random((32, 10))
y = np.random.random((10,))
y = np.expand_dims(y, axis=0)
Y = np.concatenate([y] * 32, axis=0)
Y.shape

(32, 10)

In [84]:
#Broadcast
def naive_add_matrix_and_vector(x, y):
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] += y[j]
  return x

In [85]:
import numpy as np

x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)   #Broadcast
z.shape

(64, 3, 32, 10)

In [86]:
x = np.random.random((32,))
y = np.random.random((32,))
z = np.dot(x, y)   #Dot product
z

np.float64(9.697741436842845)

In [87]:
def naive_vector_dot(x, y):   #Dot product
  assert len(x.shape) == 1
  assert len(y.shape) == 1
  assert x.shape[0] == y.shape[0]
  z = 0.
  for i in range(x.shape[0]):
    z += x[i] * y[i]
  return z

In [88]:
def naive_matrix_vector_dot(x, y):   #Matrix multiplication between a matrix and a vector
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]
  z = np.zeros(x.shape[0])
  for i in range(x.shape[0]):
    #for j in range(x.shape[1]):
    #  z[i] += x[i, j] * y[j]
    z[i] = naive_vector_dot(x[i, :], y)
  return z

In [89]:
def naive_matrix_dot(x, y):   #Matrix multiplication
  assert len(x.shape) == 2
  assert len(y.shape) == 2
  assert x.shape[1] == y.shape[0]
  z = np.zeros((x.shape[0], y.shape[1]))
  for i in range(x.shape[0]):
    for j in range(y.shape[1]):
      row_x = x[i, :]
      column_y = y[:, j]
      z[i, j] = naive_vector_dot(row_x, column_y)
  return z

In [90]:
x = np.array([[0., 1.],
              [2., 3.],
              [4., 5.]])
x.shape

(3, 2)

In [91]:
x = x.reshape((6, 1))
x

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [92]:
x = x.reshape((2, 3))
x

array([[0., 1., 2.],
       [3., 4., 5.]])

In [93]:
x = np.zeros((300, 20))
x = np.transpose(x)
x.shape

(20, 300)