<a href="https://colab.research.google.com/github/FabrizioBettetti/Machine-learning/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

In [2]:
numpy.__version__

'2.0.2'

In [3]:
import numpy as np   #Efficient storage AND operations

In [4]:
np?

In [5]:
import array   #Fixed-type data buffer. Efficient storage

In [6]:
L = list(range(10))
A = array.array('i', L)   #'i': integer
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x = np.array(12)
x

array(12)

In [8]:
x.ndim

0

In [9]:
x = np.array([12, 3, 6, 14, 7])
x

array([12,  3,  6, 14,  7])

In [10]:
x.ndim

1

In [11]:
np.array([3.14, 4, 2, 3])   #Upcasting

array([3.14, 4.  , 2.  , 3.  ])

In [12]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [13]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
x.ndim

2

In [15]:
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
x.ndim

3

In [16]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [19]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
np.random.random((3, 3))   #Uniform distribution in [0, 1)

array([[0.9874663 , 0.73706682, 0.73526746],
       [0.55510279, 0.36087258, 0.87787929],
       [0.41887752, 0.12880206, 0.00994709]])

In [22]:
np.random.normal(0, 1, (3, 3))   #Normal distribution with mean = 0 and standard deviation = 1

array([[ 0.53673799, -0.63928596,  0.7164006 ],
       [-1.47386607, -0.52287291,  1.10206747],
       [-0.23238287,  1.30177801,  0.26908828]])

In [23]:
np.random.randint(0, 10, (3, 3))   #Discrete uniform distribution in [0, 10)

array([[1, 3, 1],
       [1, 9, 9],
       [7, 4, 4]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
#Create an uninitialized array of three integers.
#The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [26]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [27]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [28]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))
#[0, 10)

In [29]:
print('x3 ndim:', x3.ndim)
print('x3 shape:', x3.shape)
print('x3 size:', x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [30]:
print('dtype:', x3.dtype)

dtype: int64


In [31]:
print('itemsize:', x3.itemsize, 'bytes')
print('nbytes:', x3.nbytes, 'bytes')

itemsize: 8 bytes
nbytes: 480 bytes


In [32]:
def naive_relu(x):
  assert len(x.shape) == 2
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] = max(x[i, j], 0)
  return x

In [33]:
def naive_add(x, y):
  assert len(x.shape) == 2
  assert x.shape == y.shape
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] += y[i, j]
  return x

In [34]:
import time

x = np.random.random((20, 100))   #Matrix 20 x 100
y = np.random.random((20, 100))

t0 = time.time()
for _ in range(1000):
  z = x + y
  z = np.maximum(z, 0.)
print('Took: {0:.2f} s'.format(time.time() - t0))

Took: 0.01 s


In [35]:
t0 = time.time()
for _ in range(1000):
  z = naive_add(x, y)
  z = naive_relu(z)
print('Took: {0:.2f} s'.format(time.time() - t0))

Took: 5.88 s


In [36]:
import numpy as np

#Broadcast
x = np.random.random((32, 10))
y = np.random.random((10,))
y = np.expand_dims(y, axis=0)
Y = np.concatenate([y] * 32, axis=0)
Y.shape

(32, 10)

In [37]:
#Broadcast
def naive_add_matrix_and_vector(x, y):
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] += y[j]
  return x

In [38]:
import numpy as np

x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)   #Broadcast
z.shape

(64, 3, 32, 10)

In [39]:
x = np.random.random((32,))
y = np.random.random((32,))
z = np.dot(x, y)   #Dot product
z

np.float64(9.697741436842845)

In [40]:
def naive_vector_dot(x, y):   #Dot product
  assert len(x.shape) == 1
  assert len(y.shape) == 1
  assert x.shape[0] == y.shape[0]
  z = 0.
  for i in range(x.shape[0]):
    z += x[i] * y[i]
  return z

In [41]:
def naive_matrix_vector_dot(x, y):   #Matrix multiplication between a matrix and a vector
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]
  z = np.zeros(x.shape[0])
  for i in range(x.shape[0]):
    #for j in range(x.shape[1]):
    #  z[i] += x[i, j] * y[j]
    z[i] = naive_vector_dot(x[i, :], y)
  return z

In [42]:
def naive_matrix_dot(x, y):   #Matrix multiplication
  assert len(x.shape) == 2
  assert len(y.shape) == 2
  assert x.shape[1] == y.shape[0]
  z = np.zeros((x.shape[0], y.shape[1]))
  for i in range(x.shape[0]):
    for j in range(y.shape[1]):
      row_x = x[i, :]
      column_y = y[:, j]
      z[i, j] = naive_vector_dot(row_x, column_y)
  return z

In [43]:
x = np.array([[0., 1.],
              [2., 3.],
              [4., 5.]])
x.shape

(3, 2)

In [44]:
x = x.reshape((6, 1))
x

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [45]:
x = x.reshape((2, 3))
x

array([[0., 1., 2.],
       [3., 4., 5.]])

In [46]:
x = np.zeros((300, 20))
x = np.transpose(x)
x.shape

(20, 300)