<a href="https://colab.research.google.com/github/FabrizioBettetti/Machine-learning/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

In [2]:
numpy.__version__

'2.0.2'

In [3]:
import numpy as np   #Efficient storage AND operations

In [4]:
np?

In [5]:
import array   #Fixed-type data buffer. Efficient storage

In [6]:
L = list(range(10))
A = array.array('i', L)   #'i': integer
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x = np.array(12)
x

array(12)

In [8]:
x.ndim

0

In [9]:
x = np.array([12, 3, 6, 14, 7])
x

array([12,  3,  6, 14,  7])

In [10]:
x.ndim

1

In [11]:
np.array([3.14, 4, 2, 3])   #Upcasting

array([3.14, 4.  , 2.  , 3.  ])

In [12]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [13]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
x.ndim

2

In [15]:
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
x.ndim

3

In [16]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [19]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
np.random.random((3, 3))   #Uniform distribution in [0, 1)

array([[0.36088284, 0.34761977, 0.69157799],
       [0.82959607, 0.7506574 , 0.21550241],
       [0.91737749, 0.74749994, 0.97932371]])

In [22]:
np.random.normal(0, 1, (3, 3))   #Normal distribution with mean = 0 and standard deviation = 1

array([[ 1.0886446 ,  0.09193486, -0.74404149],
       [-1.2315604 ,  0.28162353,  1.29869026],
       [-1.14490311,  2.30200227,  1.30723139]])

In [23]:
np.random.randint(0, 10, (3, 3))   #Discrete uniform distribution in [0, 10)

array([[4, 2, 2],
       [5, 2, 7],
       [4, 8, 8]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
#Create an uninitialized array of three integers.
#The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [26]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [27]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [28]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))
#Discrete uniform distribution in [0, 10)

In [29]:
print('x3 ndim:', x3.ndim)
print('x3 shape:', x3.shape)
print('x3 size:', x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [30]:
print('dtype:', x3.dtype)

dtype: int64


In [31]:
print('itemsize:', x3.itemsize, 'bytes')
print('nbytes:', x3.nbytes, 'bytes')

itemsize: 8 bytes
nbytes: 480 bytes


In [32]:
x1

array([5, 0, 3, 3, 7, 9])

In [33]:
x1[0]

np.int64(5)

In [34]:
x1[4]

np.int64(7)

In [35]:
x1[-1]

np.int64(9)

In [36]:
x1[-2]

np.int64(7)

In [37]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [38]:
x2[0, 0]

np.int64(3)

In [39]:
x2[2, 0]

np.int64(1)

In [40]:
x2[2, -1]

np.int64(7)

In [41]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [42]:
x1[0] = 3.14159   #Truncated because of integer dtype array
x1

array([3, 0, 3, 3, 7, 9])

In [43]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x[:5]

array([0, 1, 2, 3, 4])

In [45]:
x[5:]

array([5, 6, 7, 8, 9])

In [46]:
x[4:7]

array([4, 5, 6])

In [47]:
x[::2]

array([0, 2, 4, 6, 8])

In [48]:
x[1::2]

array([1, 3, 5, 7, 9])

In [49]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [50]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
x[5::-2]

array([5, 3, 1])

In [52]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [53]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [54]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [55]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [56]:
x2[:, 0]

array([12,  7,  1])

In [57]:
print(x2[:, 0])

[12  7  1]


In [58]:
x2[0, :]

array([12,  5,  2,  4])

In [59]:
print(x2[0, :])

[12  5  2  4]


In [60]:
print(x2[0])   #Equivalent to x2[0, :]. Only in case of row access!

[12  5  2  4]


In [61]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [62]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [63]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [64]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [65]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [66]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [67]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [68]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [70]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [71]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [72]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [73]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [74]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [75]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])   #Concatenate along the first axis

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [76]:
np.concatenate([grid, grid], axis=1)   #Concatenate along the second axis

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [77]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [78]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [79]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])   #Split before indexes 3 and 5
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [80]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [82]:
np.vsplit(grid, [1, 2])

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [83]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [84]:
np.random.seed(0)

def compute_reciprocals(values):
  output = np.empty(len(values))
  for i in range(len(values)):
    output[i] = 1.0 / values[i]
  return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [85]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

2.96 s ± 1.6 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [86]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [87]:
%timeit 1.0 / big_array

1.95 ms ± 226 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [88]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [89]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [90]:
x = np.arange(4)
print('x     =', x)
print('x + 5 =', x + 5)
print('x - 5 =', x - 5)
print('x * 2 =', x * 2)
print('x / 2 =', x / 2)
print('x // 2 =', x // 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [91]:
print('-x     =', -x)
print('x ** 2 =', x ** 2)
print('x % 2  =', x % 2)

-x     = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2  = [0 1 0 1]


In [92]:
-(0.5 * x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [93]:
np.add(x, 2)

array([2, 3, 4, 5])

In [94]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)   #Python

array([2, 1, 0, 1, 2])

In [95]:
np.absolute(x)   #Numpy

array([2, 1, 0, 1, 2])

In [96]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [97]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [98]:
theta = np.linspace(0, np.pi, 3)
print('theta      =', theta)
print('sin(theta) =', np.sin(theta))
print('cos(theta) =', np.cos(theta))
print('tan(theta) =', np.tan(theta))

theta      = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [99]:
x = [-1, 0, 1]
print('x         =', x)
print('arcsin(x) =', np.arcsin(x))
print('arccos(x) =', np.arccos(x))
print('arctan(x) =', np.arctan(x))

x         = [-1, 0, 1]
arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


In [100]:
x = [1, 2, 3]
print('x   =', x)
print('e^x =', np.exp(x))
print('2^x =', np.exp2(x))
print('3^x =', np.power(3, x))

x   = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [101]:
x = [1, 2, 4, 10]
print('x        =', x)
print('ln(x)    =', np.log(x))
print('log2(x)  =', np.log2(x))
print('log10(x) =', np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [102]:
x = [0, 0.001, 0.01, 0.1]
print('exp(x) - 1 =', np.expm1(x))
print('log(1 + x) =', np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [103]:
from scipy import special

In [104]:
x = [1, 5, 10]
print('gamma(x)     =', special.gamma(x))
print('ln|gamma(x)| =', special.gammaln(x))
print('beta(x, 2)   =', special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [105]:
x = np.array([0, 0.3, 0.7, 1.0])
print('erf(x)    =', special.erf(x))
print('erfc(x)   =', special.erfc(x))     #Complement of error function
print('erfinv(x) =', special.erfinv(x))   #Inverse of error function

erf(x)    = [0.         0.32862676 0.67780119 0.84270079]
erfc(x)   = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [106]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [107]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [108]:
x = np.arange(1, 6)
np.add.reduce(x)

np.int64(15)

In [109]:
np.multiply.reduce(x)

np.int64(120)

In [110]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [111]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [112]:
x = np.arange(1, 6)
np.multiply.outer(x, x)   #Product of each couple of elements in x

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [113]:
L = np.random.random(100)
sum(L)   #Python

np.float64(50.461758453195614)

In [114]:
np.sum(L)   #Numpy

np.float64(50.46175845319564)

In [115]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

126 ms ± 33.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
377 µs ± 9.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [116]:
min(big_array), max(big_array)   #Python

(np.float64(7.071203171893359e-07), np.float64(0.9999997207656334))

In [117]:
np.min(big_array), np.max(big_array)   #Numpy

(np.float64(7.071203171893359e-07), np.float64(0.9999997207656334))

In [118]:
%timeit min(big_array)
%timeit np.min(big_array)

81 ms ± 26.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
377 µs ± 13.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [119]:
print(big_array.min(), big_array.max(), big_array.sum())

7.071203171893359e-07 0.9999997207656334 500216.8034810001


In [120]:
M = np.random.random((3, 4))
print(M)

[[0.79832448 0.44923861 0.95274259 0.03193135]
 [0.18441813 0.71417358 0.76371195 0.11957117]
 [0.37578601 0.11936151 0.37497044 0.22944653]]


In [121]:
M.sum()

np.float64(5.1136763453287335)

In [122]:
M.min(axis=0)

array([0.18441813, 0.11936151, 0.37497044, 0.03193135])

In [123]:
M.max(axis=1)

array([0.95274259, 0.76371195, 0.37578601])

In [124]:
!head -4 Datasets/president_heights.csv

order,name,height(cm)
1,George Washington,189
2,John Adams,170
3,Thomas Jefferson,189


In [125]:
import pandas as pd

In [126]:
data = pd.read_csv('Datasets/president_heights.csv')
heights = np.array(data['height(cm)'])
print(heights)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185 191 182]


In [127]:
def naive_relu(x):
  assert len(x.shape) == 2
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] = max(x[i, j], 0)
  return x

In [128]:
def naive_add(x, y):
  assert len(x.shape) == 2
  assert x.shape == y.shape
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] += y[i, j]
  return x

In [129]:
import time

x = np.random.random((20, 100))   #Matrix 20 x 100
y = np.random.random((20, 100))

t0 = time.time()
for _ in range(1000):
  z = x + y
  z = np.maximum(z, 0.)
print('Took: {0:.2f} s'.format(time.time() - t0))

Took: 0.01 s


In [130]:
t0 = time.time()
for _ in range(1000):
  z = naive_add(x, y)
  z = naive_relu(z)
print('Took: {0:.2f} s'.format(time.time() - t0))

Took: 1.82 s


In [131]:
import numpy as np

#Broadcast
x = np.random.random((32, 10))
y = np.random.random((10,))
y = np.expand_dims(y, axis=0)
Y = np.concatenate([y] * 32, axis=0)
Y.shape

(32, 10)

In [132]:
#Broadcast
def naive_add_matrix_and_vector(x, y):
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] += y[j]
  return x

In [133]:
import numpy as np

x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)   #Broadcast
z.shape

(64, 3, 32, 10)

In [134]:
x = np.random.random((32,))
y = np.random.random((32,))
z = np.dot(x, y)   #Dot product
z

np.float64(6.270812549409618)

In [135]:
def naive_vector_dot(x, y):   #Dot product
  assert len(x.shape) == 1
  assert len(y.shape) == 1
  assert x.shape[0] == y.shape[0]
  z = 0.
  for i in range(x.shape[0]):
    z += x[i] * y[i]
  return z

In [136]:
def naive_matrix_vector_dot(x, y):   #Matrix multiplication between a matrix and a vector
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]
  z = np.zeros(x.shape[0])
  for i in range(x.shape[0]):
    #for j in range(x.shape[1]):
    #  z[i] += x[i, j] * y[j]
    z[i] = naive_vector_dot(x[i, :], y)
  return z

In [137]:
def naive_matrix_dot(x, y):   #Matrix multiplication
  assert len(x.shape) == 2
  assert len(y.shape) == 2
  assert x.shape[1] == y.shape[0]
  z = np.zeros((x.shape[0], y.shape[1]))
  for i in range(x.shape[0]):
    for j in range(y.shape[1]):
      row_x = x[i, :]
      column_y = y[:, j]
      z[i, j] = naive_vector_dot(row_x, column_y)
  return z

In [138]:
x = np.array([[0., 1.],
              [2., 3.],
              [4., 5.]])
x.shape

(3, 2)

In [139]:
x = x.reshape((6, 1))
x

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [140]:
x = x.reshape((2, 3))
x

array([[0., 1., 2.],
       [3., 4., 5.]])

In [141]:
x = np.zeros((300, 20))
x = np.transpose(x)
x.shape

(20, 300)