<a href="https://colab.research.google.com/github/FabrizioBettetti/Machine_learning/blob/main/Pandas_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction

In [ ]:
import pandas

In [ ]:
pandas.__version__

'2.2.2'

In [ ]:
import pandas as pd

In [ ]:
pd?

In [ ]:
import numpy as np

#Introducing pandas objects

##The pandas series object

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [ ]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [ ]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
data[1]

np.float64(0.5)

In [ ]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [ ]:
data['b']

np.float64(0.5)

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [ ]:
data[5]

np.float64(0.5)

In [ ]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)   #Default behavior: index = keys
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [ ]:
population['California']

np.int64(38332521)

In [ ]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [ ]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [ ]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [ ]:
pd.Series({2: 'a', 1: 'b', 3: 'c'})

2    a
1    b
3    c
dtype: object

In [ ]:
pd.Series({2: 'a', 1: 'b', 3: 'c'}, index=[3, 2])

3    c
2    a
dtype: object

##The pandas dataframe object

In [ ]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [ ]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [ ]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [ ]:
states.columns

Index(['population', 'area'], dtype='object')

In [ ]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [ ]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [ ]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [ ]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [ ]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.156243  0.132503
b  0.816746  0.164569
c  0.842698  0.860327

In [ ]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

##The pandas index object

In [ ]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [ ]:
ind[1]

np.int64(3)

In [ ]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [ ]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [ ]:
#ind[1] = 0   #Error: Index objects are immutable

In [ ]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

indA.intersection(indB)   ###Verifica!

Index([3, 5, 7], dtype='int64')

In [ ]:
indA.union(indB)

Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [ ]:
indA.symmetric_difference(indB)   #(A \ B) U (B \ A)

Index([1, 2, 9, 11], dtype='int64')

#Data indexing and selection

##Data selection in series

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [ ]:
data['b']

np.float64(0.5)

In [ ]:
'a' in data   #Like dictionaries

True

In [ ]:
data.keys()   #Like dictionaries

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
list(data.items())   #Like dictionaries   ###Verifica!

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [ ]:
data['e'] = 1.25   #Extend series like a dictionary
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [ ]:
data['a':'c']   #Slicing by explicit index (with explicit index 'c' is INCLUDED)

a    0.25
b    0.50
c    0.75
dtype: float64

In [ ]:
data[0:2]   #Slicing by implicit integer index (with implicit index 2 is EXCLUDED)

a    0.25
b    0.50
dtype: float64

In [ ]:
data[(data > 0.3) & (data < 0.8)]   #Masking

b    0.50
c    0.75
dtype: float64

In [ ]:
data[['a', 'e']]   #Fancy index

a    0.25
e    1.25
dtype: float64

In [ ]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [ ]:
data[1]   #With EXPLICIT INTEGER indices, in data[1], 1 is an EXPLICIT index

'a'

In [ ]:
data[1:3]   #With EXPLICIT INTEGER indices, slicing refers to IMPLICIT indeces

3    b
5    c
dtype: object

In [ ]:
#loc: explicit index
data.loc[1]

'a'

In [ ]:
data.loc[1:3]

1    a
3    b
dtype: object

In [ ]:
#iloc: implicit index
data.iloc[1]

'b'

In [ ]:
data.iloc[1:3]

3    b
5    c
dtype: object

##Data selection in DataFrame

In [ ]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area': area, 'pop': pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [ ]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [ ]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [ ]:
data.area is data['area']   #Same object

True

In [ ]:
data.pop is data['pop']   #pop is a method of the DataFrame and cannot be used as a column name attribute.
                          #In this case use data['pop'] = z rather than data.pop = z

False

In [ ]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [ ]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [ ]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [ ]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [ ]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [ ]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [ ]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [ ]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [ ]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [ ]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [ ]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [ ]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

#Operating on data in pandas

##Ufuncs: index preservation

In [ ]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [ ]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [ ]:
np.exp(ser)   #Indices preserved

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [ ]:
np.sin(df * np.pi / 4)   #Indices and columns preserved

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

##Ufuncs: index alignment

In [ ]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [ ]:
area

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [ ]:
population / area   #Contains the union of the indices

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [ ]:
area.index.union(population.index)

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [ ]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [ ]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [ ]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [ ]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [ ]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [ ]:
A.stack()

0  A     1
   B    11
1  A     5
   B     1
dtype: int64

In [ ]:
fill = A.stack().mean()   #Mean of the entire dataframe A
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

##Ufuncs: operations between dataframe and series

In [ ]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [ ]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [ ]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [ ]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [ ]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int64

In [ ]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

#Handling missing data

##Missing data in pandas

In [ ]:
vals1 = np.array([1, None, 3, 2])   #dtype = object
vals1
#None: python way for missing value

array([1, None, 3, 2], dtype=object)

In [ ]:
for dtype in ['object', 'int']:
  print('dtype =', dtype)
  %timeit np.arange(1E6, dtype=dtype).sum()
  print()
#int faster than object beacuse object operations will be done at python level instead of numpy level

dtype = object
65.9 ms ± 2.66 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
992 µs ± 194 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



In [ ]:
#vals1.sum()   #Error because of None

In [ ]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype
#NaN is floating point --> fast operations in numpy

dtype('float64')

In [ ]:
1 + np.nan

nan

In [ ]:
0 * np.nan

nan

In [ ]:
vals2.sum(), vals2.min(), vals2.max()

(np.float64(nan), np.float64(nan), np.float64(nan))

In [ ]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)   #Ignore missing values

(np.float64(8.0), np.float64(1.0), np.float64(4.0))

In [ ]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [ ]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [ ]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

##Operating on null values

In [ ]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [ ]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [ ]:
data.dropna()

0        1
2    hello
dtype: object

In [ ]:
df = pd.DataFrame([[1, np.nan, 2],
                   [2,      3, 5],
                   [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [ ]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [ ]:
df.dropna(axis=1)

2
0  2
1  5
2  6

In [ ]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [ ]:
df.dropna(axis='columns', how='all')   #Drop columns with ALL NaN

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [ ]:
df.dropna(axis='rows', thresh=3)   #Drop rows with < 3 NON-null values

0    1  2   3
1  2.0  3.0  5 NaN

In [ ]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [ ]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [ ]:
data.ffill()   #Fill NA with the previous non-null value

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [ ]:
data.bfill()   #Fill NA with the next non-null value

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [ ]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [ ]:
df.ffill(axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

#Hierarchical indexing

##A multiply indexed series

In [ ]:
#Bad way
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

In [ ]:
pop[('California', 2010):('Texas', 2000)]

In [ ]:
pop[[i for i in pop.index if i[1] == 2010]]   #Select 2010 year is not clean and not efficient

In [ ]:
#Good way
index = pd.MultiIndex.from_tuples(index)
index

In [ ]:
pop = pop.reindex(index)
pop

In [ ]:
pop[:, 2010]   #Select 2010 year is clean and efficient

In [ ]:
pop_df = pop.unstack()
pop_df

In [ ]:
pop_df.stack()

In [ ]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

In [ ]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()

##Methods of MultiIndex creation

In [ ]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

In [ ]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
pd.Series(data)

In [ ]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

In [ ]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

In [ ]:
pd.MultiIndex.from_product(['a', 'b'], [1, 2])

In [ ]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
              labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [ ]:
pop.index.names['state', 'year']

In [ ]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]], names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']], names=['subject', 'type'])

data = np.round(np.random.randn(4, 6), 1)   #1: 1 decimal place
data[:, ::2] *= 10
data += 37

health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

In [ ]:
health_data['Guido']

##Indexing and slicing a **MultiIndex**

In [ ]:
pop

In [ ]:
pop['California', 2000]

In [ ]:
pop['California']

In [ ]:
pop.loc['California':'New York']

In [ ]:
pop[:, 2000]

In [ ]:
pop[pop > 22000000]

In [ ]:
pop[['California', 'Texas']]

In [ ]:
health_data

In [ ]:
health_data['Guido', 'HR']

In [ ]:
health_data.iloc[:2, :2]

In [ ]:
health_data.loc[:, ('Bob', 'HR')]

In [ ]:
health_data.loc[(:, 1), (:, 'HR')]   #Error

In [ ]:
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

##Rearranging multi-indices

In [ ]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

In [ ]:
try:
  data['a':'b']
except KeyError as e:
  print(type(e))
  print(e)

In [ ]:
data = data.sort_index()
data

In [ ]:
data['a':'b']

In [ ]:
pop.unstack(level=0)

In [ ]:
pop.unstack(level=1)

In [ ]:
pop.unstack().stack()

In [ ]:
pop_flat = pop.reset_index(name='population')
pop_flat

In [ ]:
pop_flat.set_index(['state', 'year'])

##Data aggregations on multi-indices

In [ ]:
health_data

In [ ]:
data_mean = health_data.mean(level='year')
data_mean

In [ ]:
data_mean.mean(axis=1, level='type')

#Combining datasets: concat and append

In [ ]:
def make_df(cols, ind):
  data = {c: [str(c) + str(i) for i in ind] for c in cols}
  return pd.DataFrame(data, ind)

In [ ]:
make_df('ABC', range(3))

##Recall: concatenation of numpy arrays

In [ ]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

In [ ]:
x = [[1, 2],
     [3, 4]]
np.concatenate([x, x], axis=1)

##Simple concatenation with pd.concat

In [ ]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

In [ ]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1); print(df2); print(pd.concat([df1, df2]))

In [ ]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
print(df3); print(df4); print(pd.concat([df3, df4], axis='col'))

In [ ]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])
y.index = x.index   #Make duplicate indices!
print(x); print(y); print(pd.concat([x, y]))

In [ ]:
try:
  pd.concat([x, y], verify_integrity=True)   #Check if there are overlapping indexes
except ValueError as e:
  print('ValueError:', e)

In [ ]:
print(x); print(y); print(pd.concat([x, y]), ignore_index=True)   #Concatenate with a new set of integer indexes

In [ ]:
print(x); print(y); print(pd.concat([x, y], keys=['x', 'y']))

In [ ]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
print(df5); print(df6); print(pd.concat([df5, df6]));

In [ ]:
print(df5); print(df6); print(pd.concat([df5, df6], join='inner'))

In [ ]:
print(df5); print(df6); print(pd.concat([df5, df6], join_axes=[df5.columns]))

In [ ]:
print(df1); print(df2); print(df1.append(df2))

#Combining datasets: merge and join

##Categories of joins

In [ ]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
print(df1); print(df2)

In [ ]:
df3 = pd.merge(df1, df2)

In [ ]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
print(df3); print(df4); print(pd.merge(df3, df4))

In [ ]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting', 'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux', 'spreadsheets', 'organization']})
print(df1); print(df5); print(pd.merge(df1, df5))

##Specification of the merge key

In [ ]:
print(df1); print(df2); print(pd.merge(df1, df2, on='employee'))

In [ ]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
print(df1); print(df3);
print(pd.merge(df1, df3, left_on="employee", right_on="name"))   #In case of columns with different names but coherent

In [ ]:
pd.merge(df1, df3, left_on='employee', right_on='name').drop('name', axis=1)   #Drop the redundant column

In [ ]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
print(df1a);  print(df2a)

In [ ]:
print(df1a); print(df2a);
print(pd.merge(df1a, df2a, left_index=True, right_index=True))

In [ ]:
print(df1a); print(df2a); print(df1a.join(df2a))   #Join merge on indices, by default

In [ ]:
print(df1a); print(df3);
print(pd.merge(df1a, df3, left_index=True, right_on='name'))

##Specifying set arithmetic for joins

In [ ]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])
print(df6); print(df7); print(pd.merge(df6, df7))

In [ ]:
pd.merge(df6, df7, how='inner')

In [ ]:
print(df6); print(df7); print(pd.merge(df6, df7, how='outer'))

In [ ]:
print(df6); print(df7); print(pd.merge(df6, df7, how='left'))

##Overlapping column names: the suffixes keyword

In [ ]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [3, 1, 4, 2]})
print(df8); print(df9); print(pd.merge(df8, df9, on='name'))

In [ ]:
print(df8); print(df9);
print(pd.merge(df8, df9, on='name', suffixes=['_L', '_R']))

##Example: US states data

In [ ]:
pop = pd.read_csv('Datasets/state-population.csv')
areas = pd.read_csv('Datasets/state-areas.csv')
abbrevs = pd.read_csv('Datasets/state-abbrevs.csv')

print(pop.head()); print(areas.head()); print(abbrevs.head())

In [ ]:
merged = pd.merge(pop, abbrevs, how='outer', left_on='state/region', right_on='abbreviation')
merged = merged.drop('abbreviation', 1)
merged.head()

In [ ]:
merged.isnull().any()

In [ ]:
merged[merged['population'].isnull()].head()